[package]
name = "core"
version = "0.1.0"
authors = ["Matthias Lochbrunner <matthias_lochbrunner@web.de>"]
edition = "2018"

[dependencies]
nom = "^4.2"
maplit = "^1.0.1"
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
bincode="1.1.4"
chrono="0.4.6"

[dev-dependencies]
p-macro = "*"