name: basics
files:
  evaluation-results: experiments/evaluation-results.yaml
  model: &model experiments/basics/basics.sp
  new-rules: &new-rules experiments/basics/new-rules.yaml
  scenario: real_world_problems/basics/dataset.yaml
  solver-trainings-data: &solver-data experiments/basics/solver-trainings-data.bin
  training-statistics: &training-statistics experiments/training-statistics.yaml
  trainings-data-traces: experiments/bag-basic_*.tr
  trainings-data: &bag experiments/bag-basic.bin
  working-folder: experiments
  t3-loop-traces: experiments/basics/t3-loop-results.spb
  solver-traces: experiments/basics/solver-results.spb
generation:
  stages: []
  max-depth: 10
  max-size: 127
  min-working-density: 0.1
  min-result-density: 0.05
  distribution-suppression-exponent: 1.8
  augmentation:
    enabled: true # Permuting free variables
    factor: 10
  blacklist-pattern:
    - (1*1)*(1*1)
    - (0+0)+(0+0)
    - 0-(0-0)
    - (1^1)^(1^1)
training:
  save-model: *model
  device: cpu
  # Learning
  num-epochs: 1
  report-rate: 2
  batch-size: 32
  learning-rate: 0.1 # Not needed here
  gradient-clipping: 0.1
  value-loss-weight: 0.5
  model-name: TreeCnnSegmenter
  # Scenario
  scenario: bag
  filename: *bag
  statistics: *training-statistics
  data-size-limit: -1
  model-parameter:
    embedding_size: 24
    hidden_layers: 2
    dropout: 0
    use_props: False
fine-tuning:
  learning-rate: 0.01
evaluation:
  num-epochs: 10
  problems:
    beam-size: 10
    num_epochs: 30
    max_track_loss: 3
    max_fit_results: 1000
    iterations: 3
    # white-list:
    #   - a*x = a*b
  training-data:
    beam-size: "1:15"
    max-steps: -1
  solver-trainings-data: *solver-data
  max-size: 11
  max-grow: 2
  new-rules-filename: *new-rules
  black-list-terms:
    []
    # - 0 + (x - 1) = a
    # - a = x + -1

  black-list-rules: []
