GET http://127.0.0.1:5000/api/sample/1



###



GET http://127.0.0.1:5000/api/length




###



GET http://127.0.0.1:5000/api/overview?begin=0&end=10




###



GET http://127.0.0.1:5000/api/histogram

