name: smoker

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install pyyaml
            pip3 install ci/iconv-0.2.1-cp37-cp37m-linux_x86_64.whl
            pip3 install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Create Trainings Data
        run: cargo run --release --bin generator -- -c real_world_problems/basics/dataset.yaml --stages 3 3
      - name: Run Training
        run: PYTHONPATH=ml python3 ./ml/train.py --device cpu -c real_world_problems/basics/dataset.yaml -v --data-size-limit 100 -n 1